version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: adotapet-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: adotapet
      POSTGRES_PASSWORD: adotapet123
      POSTGRES_DB: adotapet
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/backend/config/seed.sql:/docker-entrypoint-initdb.d/01-seed.sql

volumes:
  pgdata:
